# Generated by Django 3.1.5 on 2021-01-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210123_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('dean', models.CharField(max_length=100, null=True)),
                ('deanMail', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
