# Generated by Django 3.1.5 on 2021-01-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210123_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('avgSalary', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='degrees',
            name='faculty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.faculties'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degrees',
            name='jobs',
            field=models.ManyToManyField(to='project.Jobs'),
        ),
    ]
