# Generated by Django 3.1.5 on 2021-01-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210123_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='degree',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.degree'),
            preserve_default=False,
        ),
    ]
