# Generated by Django 3.1.5 on 2021-01-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20210123_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='preReq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.degree'),
        ),
    ]
