# Generated by Django 3.1.5 on 2021-01-23 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_degree_prereq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
