# Generated by Django 3.1.5 on 2021-01-23 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210123_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='website',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/#', max_length=100, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
