# Generated by Django 3.1.5 on 2021-01-23 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20210123_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultie',
            name='dean',
        ),
        migrations.RemoveField(
            model_name='facultie',
            name='deanMail',
        ),
        migrations.AddField(
            model_name='facultie',
            name='degrees',
            field=models.ManyToManyField(to='project.Degree'),
        ),
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('collegeWork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.college')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.facultie')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='deans',
            field=models.ManyToManyField(to='project.Dean'),
        ),
    ]
