# Generated by Django 3.1.5 on 2021-01-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20210123_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='degrees',
            field=models.ManyToManyField(to='project.Degree'),
        ),
    ]
