# Generated by Django 3.1.5 on 2021-01-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_college_degrees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='degree',
            new_name='reqDegree',
        ),
        migrations.AddField(
            model_name='degree',
            name='jobs',
            field=models.ManyToManyField(to='project.Job'),
        ),
    ]
