# Generated by Django 3.1.5 on 2021-01-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20210123_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='jobs',
            field=models.ManyToManyField(blank=True, null=True, to='project.Job'),
        ),
    ]
