# Generated by Django 3.1.5 on 2021-01-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20210123_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='faculty',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.facultie'),
        ),
    ]
