# Generated by Django 3.1.5 on 2021-01-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_cuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='isAdmin',
            field=models.BooleanField(null=True),
        ),
    ]
