# Generated by Django 3.1.5 on 2021-01-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20210124_0405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactF',
        ),
    ]
