# Generated by Django 3.1.5 on 2021-01-24 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20210124_0417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactF',
            new_name='ContactFM',
        ),
    ]
