# Generated by Django 3.1.5 on 2021-01-24 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_auto_20210124_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactfm',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='dean',
            name='email',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
