# Generated by Django 3.1.5 on 2021-01-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_auto_20210124_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='faculty',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='project.facultie'),
        ),
        migrations.AlterField(
            model_name='facultie',
            name='degrees',
            field=models.ManyToManyField(null=True, to='project.Degree'),
        ),
    ]
