# Generated by Django 3.1.5 on 2021-01-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_auto_20210124_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultie',
            name='degrees',
            field=models.ManyToManyField(blank=True, to='project.Degree'),
        ),
    ]
