# Generated by Django 3.1.5 on 2021-01-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20210124_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='reqDegree',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.degree'),
        ),
    ]
