# Generated by Django 3.1.5 on 2021-01-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_auto_20210124_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='deans',
            field=models.ManyToManyField(blank=True, to='project.Dean'),
        ),
    ]
